export const apiConfig = {
    "HttpApiId":  "gmwvbhostj",
    "UploadFilesToS3LambdaFunctionQualifiedArn":  "arn:aws:lambda:us-east-1:992382408780:function:emotio-x-backend-dev-uploadFilesToS3:18",
    "GetUserByIdLambdaFunctionQualifiedArn":  "arn:aws:lambda:us-east-1:992382408780:function:emotio-x-backend-dev-getUserById:18",
    "DefaultHandlerLambdaFunctionQualifiedArn":  "arn:aws:lambda:us-east-1:992382408780:function:emotio-x-backend-dev-defaultHandler:11",
    "SendMessageLambdaFunctionQualifiedArn":  "arn:aws:lambda:us-east-1:992382408780:function:emotio-x-backend-dev-sendMessage:15",
    "ServiceEndpointWebsocket":  "wss://nu4h7hwjej.execute-api.us-east-1.amazonaws.com/dev",
    "WebSocketApiEndpoint":  "wss://ckcs560m8k.execute-api.us-east-1.amazonaws.com/dev",
    "DisconnectLambdaFunctionQualifiedArn":  "arn:aws:lambda:us-east-1:992382408780:function:emotio-x-backend-dev-disconnect:18",
    "LoginUserLambdaFunctionQualifiedArn":  "arn:aws:lambda:us-east-1:992382408780:function:emotio-x-backend-dev-loginUser:18",
    "UpdateUserByIdLambdaFunctionQualifiedArn":  "arn:aws:lambda:us-east-1:992382408780:function:emotio-x-backend-dev-updateUserById:17",
    "GetAllUsersLambdaFunctionQualifiedArn":  "arn:aws:lambda:us-east-1:992382408780:function:emotio-x-backend-dev-getAllUsers:18",
    "S3BucketName":  "emotio-x-backend-dev-deployment-bucket",
    "HttpApiUrl":  "https://gmwvbhostj.execute-api.us-east-1.amazonaws.com",
    "SendTemporaryPasswordLambdaFunctionQualifiedArn":  "arn:aws:lambda:us-east-1:992382408780:function:emotio-x-backend-dev-sendTemporaryPassword:18",
    "DeleteUserByIdLambdaFunctionQualifiedArn":  "arn:aws:lambda:us-east-1:992382408780:function:emotio-x-backend-dev-deleteUserById:17",
    "ConnectLambdaFunctionQualifiedArn":  "arn:aws:lambda:us-east-1:992382408780:function:emotio-x-backend-dev-connect:18",
    "RefreshLambdaFunctionQualifiedArn":  "arn:aws:lambda:us-east-1:992382408780:function:emotio-x-backend-dev-refresh:17",
    "ServerlessDeploymentBucketName":  "emotio-x-backend-dev-serverlessdeploymentbucket-ds7zdmzqlruu",
    "ApiUrl":  "https://gmwvbhostj.execute-api.us-east-1.amazonaws.com",
    "CreateResearchLambdaFunctionQualifiedArn":  "arn:aws:lambda:us-east-1:992382408780:function:emotio-x-backend-dev-createResearch:17",
    "LogoutUserLambdaFunctionQualifiedArn":  "arn:aws:lambda:us-east-1:992382408780:function:emotio-x-backend-dev-logoutUser:18",
    "RegisterUserLambdaFunctionQualifiedArn":  "arn:aws:lambda:us-east-1:992382408780:function:emotio-x-backend-dev-registerUser:18",
    "GeneratePresignedUrlsLambdaFunctionQualifiedArn":  "arn:aws:lambda:us-east-1:992382408780:function:emotio-x-backend-dev-generatePresignedUrls:17",
    "RefreshTokenLambdaFunctionQualifiedArn":  "arn:aws:lambda:us-east-1:992382408780:function:emotio-x-backend-dev-refreshToken:18"
}
